### PR TITLE
move occupation US SOC ID in a separate module

### PR DESCRIPTION
**Pull request by zhengj2007**

### CODE REVIEW

**Comment by johnbeve** [comment]
@smithGit @yongqunh @zhengj2007 Why are separate modules being created? We did not discuss this.

**Comment by smithGit** [comment]
I have taken no recent (3+ months) action on the OccO info, so I am hoping either Jie or Oliver can address this.  Sam

**Comment by zhengj2007** [comment]
> @smithGit @yongqunh @zhengj2007 Why are separate modules being created? We did not discuss this.

@johnbeve The modules created based on the design patterns. It allows us to create the terms using templates in tab-delimited format files and convert to the OWL format using Robot template command. See the [wiki pages](https://github.com/Occupation-Ontology/OccO/wiki/OccO-Editing). So, we don't need to add/edit the term manually using Protege. Besides, it is easy to maintain the ontology and keep the terms implemented consistently. We can discuss the design patterns and adjust the templates if needed.

**Comment by johnbeve** [comment]
@zhengj2007 I understand templates and design patterns. It seems to me that you've unilaterally made changes to the main branch of a collaborative project without collaborating with other members of the group. 

Either (1) you should've created a PR for review before merging or (2) we should've agreed as a group to these updates before they were implemented.

**Comment by zhengj2007** [comment]
@johnbeve I created the pull requests for all the changes I made. I merge the changes for including the Alabama terms and creating the views for the coming Alabama meeting. If you prefer, I can redo the merge and assign you to review all the changes I made. Please let me know if you'd like me to redo the merge. In the future, I won't merge the pull requests before reviewing.

**Pull request merged**
